package ShapeTalk.Chat;

import java.awt.Rectangle;

public class frmPrivateConv extends javax.swing.JFrame {
	/** Creates new form frmMain */
	public frmPrivateConv(PrivateConversation iRef) {
		_refConv = iRef;
		initComponents();
		setSize(300, 300);
		setVisible(true);
		requestFocus();
		setTitle(_refConv.GetTo().GetName());
		typeBox.requestFocus();

	}

	public void AddRecvLine(String iMsg) {
		msgArea.setText(msgArea.getText() + iMsg + "\n");
		msgArea.scrollRectToVisible(new Rectangle(0, msgArea.getHeight() - 20,
				1, 1));
	}

	public void ClearRecvArea() {
		msgArea.setText("");
	}

	public void SendMsg() {
		if (typeBox.getText().equals("/clear")
				|| typeBox.getText().equals("/cls")) {
			ClearRecvArea();
		} else {
			_refConv.SendMessage(typeBox.getText());
		}
		typeBox.setText("");
	}

	// End of variables declaration//GEN-END:variables

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed"
	// desc=" Generated Code ">//GEN-BEGIN:initComponents
	private void initComponents() {
		typeBox = new javax.swing.JTextField();
		jScroller = new javax.swing.JScrollPane();
		msgArea = new javax.swing.JTextArea();

		setTitle("Private Conversation");
		setName("frmPrivateConv");
		typeBox.addKeyListener(new java.awt.event.KeyAdapter() {
			@Override
			public void keyTyped(java.awt.event.KeyEvent evt) {
				typeBoxKeyTyped(evt);
			}
		});

		getContentPane().add(typeBox, java.awt.BorderLayout.SOUTH);

		msgArea.setBackground(new java.awt.Color(244, 241, 241));
		msgArea.setColumns(20);
		msgArea.setEditable(false);
		msgArea.setRows(5);
		jScroller.setViewportView(msgArea);

		getContentPane().add(jScroller, java.awt.BorderLayout.CENTER);

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void typeBoxKeyTyped(java.awt.event.KeyEvent evt) {// GEN-FIRST:
		// event_typeBoxKeyTyped
		if (evt.getKeyChar() == '\n') {
			SendMsg();
		}
	}// GEN-LAST:event_typeBoxKeyTyped

	private final PrivateConversation _refConv;

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JScrollPane jScroller;

	private javax.swing.JTextArea msgArea;

	private javax.swing.JTextField typeBox;

}
